openapi: '3.0.2'
security:
  - bearerAuth: []
info:
  title: Bars
  version: '1.0'
  description: Api that manage a bar and their stock.
  contact:
    email: 'test@gmail.com'
    name: 'test'
    url: 'test.com'
servers:
  - url: https://api.server.test/v1
tags:
  - name: drinks
    description: 'Drinks'
paths:
  /drinks:
    get:
      summary: Get all drinks
      description: Get all drinks.
      operationId: getDrinks
      tags:
        - drinks
      responses:
        '200':
          description: OK
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/components/headers/X-Rate-Limit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/components/headers/X-Rate-Limit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/components/headers/X-Rate-Limit-Reset'
          content:
            application/json:
              schema:
                type: array
                maxItems: 100
                items:
                  $ref: '#/components/schemas/drink'
              examples:
                drinks_json:
                  value:
                  - name: Titan
                    price: 2.5
                    category: Beer
                  - name: Saumur
                    price: 10
                    category: Wine
                    image: https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
                  - name: Coca
                    price: 1.5
                    category: Soda
        '400':
          description: Bad Request.
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/components/headers/X-Rate-Limit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/components/headers/X-Rate-Limit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/components/headers/X-Rate-Limit-Reset'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '401':
          description: Unauthorized.
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/components/headers/X-Rate-Limit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/components/headers/X-Rate-Limit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/components/headers/X-Rate-Limit-Reset'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '429':
          description: Too Many Requests.
          headers:
            Retry-After:
              $ref: '#/components/headers/Retry-After'
            X-Rate-Limit-Limit:
              $ref: '#/components/headers/X-Rate-Limit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/components/headers/X-Rate-Limit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/components/headers/X-Rate-Limit-Reset'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '500':
          description: Internal Server Error.
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/components/headers/X-Rate-Limit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/components/headers/X-Rate-Limit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/components/headers/X-Rate-Limit-Reset'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  headers:
    X-Rate-Limit-Limit:
      description: The number of allowed requests in the current period.
      schema:
        type: integer
        format: int32
        minimum: 0
        maximum: 1000
    X-Rate-Limit-Remaining:
      description: The number of remaining requests in the current period.
      schema:
        type: integer
        format: int32
        minimum: 0
        maximum: 1000
    X-Rate-Limit-Reset:
      description: The number of seconds left in the current period.
      schema:
        type: integer
        format: int32
        minimum: 0
        maximum: 1000
    Retry-After:
      description: The number of seconds left before the request can be retried.
      schema:
        type: integer
        format: int32
        minimum: 0
        maximum: 600
  schemas:
    error:
      type: object
      description: Error response object for multiples errors.
      properties:
        message:
          type: string
          format: text
          maxLength: 100
          description: Error message
          example: Unauthorized
      required: [message]
    drink:
      type: object
      description: Drink object for multiples drinks.
      properties:
        name:
          type: string
          format: text
          maxLength: 50
          description: Name of the drink
          example: Beer
        price:
          type: number
          minimum: 0
          description: Price of the drink
          example: 2.5
        category:
          type: string
          maxLength: 50
          pattern: '^[A-Z].+$'
          description: Category of the drink
          example: Beer
        image:
          type: string
          format: uri
          maxLength: 2048
          description: Image of the drink
          example: https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
      required: [name, price, category]
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

