name: 'check contrat API'

on:
  push:
    paths: 'specification/**'
  pull_request:
    paths: 'specification/**'

jobs:
  check-contrat-API:
    runs-on: ubuntu-latest
    container:
        image: 'stoplight/spectral:6'
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      - name: 'Run spectral'
        run: spectral lint ./specification/bar.yml