name: CI

on: [push, pull_request]

jobs:
    CI:
        name: Lint and tests on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                pnpm: [8.0.0]
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: pnpm i --frozen-lockfile
            - name: Run linter
              run: pnpm lint
            - name: Run build
              run: pnpm run -r build
