name: CI

on: [push, pull_request]

jobs:
    CI:
        name: Lint and tests on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [18]
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm i --frozen-lockfile
            - name: Install playwright browsers
              run: npx playwright install --with-deps
            - name: Run linter
              run: npm run lint
            - name: Run tests end to end
              run: npm run test:e2e -w front
              env:
                  API_URL: http://localhost:3000
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: E2E test report
                  path: front/playwright-report/
                  retention-days: 10
